services:

  certbot:
    image: certbot/certbot
    container_name: "certbot"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"


  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    env_file:
      - ./env
    entrypoint: /bin/sh -c "envsubst '\$SNIPPETS_APP_PORT \$PARSE_APP_PORT \$PERMISSION_APP_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - certbot

  parse:
    image: ghcr.io/group-5-ingsis/parse:latest-dev
    container_name: "parse"
    ports:
      - ${PARSE_APP_PORT}
    environment:
      SERVER_PORT: ${PARSE_SERVER_PORT}

  snippets:
    image: ghcr.io/group-5-ingsis/snippets:latest-dev
    container_name: "snippets"
    ports:
      - ${SNIPPETS_APP_PORT}
    env_file:
      - ./env
    depends_on:
      - db-snippets

  db-snippets:
    image: postgres:13
    container_name: "db-snippets"
    env_file:
      - ./env
    ports:
      - ${SNIPPETS_DB_PORT}
    volumes:
      - db-snippets-data:/var/lib/postgresql/data

  permission:
    image: ghcr.io/group-5-ingsis/permission:latest-dev
    container_name: "permission"
    ports:
      - ${PERMISSION_APP_PORT}
    env_file:
      - ./env
    depends_on:
      - db-permission

  db-permission:
    image: postgres:13
    container_name: "db-permission"
    env_file:
      - ./env
    ports:
      - ${PERMISSION_DB_PORT}
    volumes:
      - db-permission-data:/var/lib/postgresql/data

  asset-service:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

volumes:
  db-snippets-data:
  db-permission-data:
  blob:
    external: false

