services:

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    networks:
      - snippet-searcher

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - snippet-searcher
    depends_on:
      - certbot


  parse:
    image: ghcr.io/group-5-ingsis/parse:latest-dev
    ports:
      - ${PARSE_APP_PORT}
    environment:
      SERVER_PORT: ${PARSE_SERVER_PORT}
    networks:
      - snippet-searcher

  snippets:
    image: ghcr.io/group-5-ingsis/snippets:latest-dev
    ports:
      - ${SNIPPETS_APP_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${SNIPPETS_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SNIPPETS_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SNIPPETS_DB_PASSWORD}
      SERVER_PORT: ${SNIPPETS_SERVER_PORT}
      AUTH0_AUDIENCE: ${SNIPPETS_AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${SNIPPETS_AUTH_SERVER_URI}
      AUTH_CLIENT_ID: ${SNIPPETS_AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${SNIPPETS_AUTH_CLIENT_SECRET}
    depends_on:
      - db-snippets
    networks:
      - snippet-searcher

  db-snippets:
    image: postgres:13
    environment:
      POSTGRES_USER: ${SNIPPETS_DB_USER}
      POSTGRES_PASSWORD: ${SNIPPETS_DB_PASSWORD}
      POSTGRES_DB: ${SNIPPETS_DB_NAME}
    ports:
      - ${SNIPPETS_DB_PORT}
    volumes:
      - db-snippets-data:/var/lib/postgresql/data

  permission:
    image: ghcr.io/group-5-ingsis/permission:latest-dev
    ports:
      - ${PERMISSION_APP_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${PERMISSION_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PERMISSION_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PERMISSION_DB_PASSWORD}
      SERVER_PORT: ${PERMISSION_SERVER_PORT}
      AUTH0_AUDIENCE: ${PERMISSION_AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${PERMISSION_AUTH_SERVER_URI}
      AUTH_CLIENT_ID: ${PERMISSION_AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${PERMISSION_AUTH_CLIENT_SECRET}
      AUTH_CALLBACK: ${PERMISSION_AUTH_CALLBACK}
    depends_on:
      - db-permission
    networks:
      - snippet-searcher

  db-permission:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PERMISSION_DB_USER}
      POSTGRES_PASSWORD: ${PERMISSION_DB_PASSWORD}
      POSTGRES_DB: ${PERMISSION_DB_NAME}
    ports:
      - ${PERMISSION_DB_PORT}
    volumes:
      - db-permission-data:/var/lib/postgresql/data

  asset-service:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false
    networks:
      - snippet-searcher

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

volumes:
  db-snippets-data:
  db-permission-data:
  blob:
    external: false

networks:
  snippet-searcher:
    driver: bridge
