services:
  parse-app:
    image: ghcr.io/mpiccinini/parse:latest-dev
    ports:
      - ${PARSE_APP_PORT}
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${PARSE_SERVER_PORT}

  snippets-app:
    image: ghcr.io/mpiccinini/snippets:latest-dev
    ports:
      - ${SNIPPETS_APP_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${SNIPPETS_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SNIPPETS_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SNIPPETS_DB_PASSWORD}
      SERVER_PORT: ${SNIPPETS_SERVER_PORT}
    depends_on:
      - db-snippets
      - permission-app

  permission-app:
    image: ghcr.io/mpiccinini/permission:latest-dev
    ports:
      - ${PERMISSION_APP_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${PERMISSION_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PERMISSION_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PERMISSION_DB_PASSWORD}
      SERVER_PORT: ${PERMISSION_SERVER_PORT}
    depends_on:
      - db-permission

  db-snippets:
    image: postgres:13
    environment:
      POSTGRES_USER: ${SNIPPETS_DB_USER}
      POSTGRES_PASSWORD: ${SNIPPETS_DB_PASSWORD}
      POSTGRES_DB: ${SNIPPETS_DB_NAME}
    ports:
      - ${SNIPPETS_DB_PORT}
    volumes:
      - db-snippets-data:/var/lib/postgresql/data

  db-permission:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PERMISSION_DB_USER}
      POSTGRES_PASSWORD: ${PERMISSION_DB_PASSWORD}
      POSTGRES_DB: ${PERMISSION_DB_NAME}
    ports:
      - ${PERMISSION_DB_PORT}
    volumes:
      - db-permission-data:/var/lib/postgresql/data

volumes:
  db-snippets-data:
  db-permission-data: